using Breizh360.Gateway.Observability;

namespace Breizh360.Gateway.Errors;

/// <summary>
/// Normalize errors generated by the Gateway itself (exceptions, 502, etc.).
/// Downstream API errors are forwarded as-is.
/// </summary>
public sealed class GatewayErrorMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<GatewayErrorMiddleware> _logger;

    public GatewayErrorMiddleware(RequestDelegate next, ILogger<GatewayErrorMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task Invoke(HttpContext context)
    {
        try
        {
            await _next(context);

            // Optionally, normalize some Gateway-generated statuses.
            if (context.Response.HasStarted)
                return;

            if (context.Response.StatusCode is StatusCodes.Status429TooManyRequests)
            {
                await WriteAsync(context, StatusCodes.Status429TooManyRequests, "RATE_LIMITED", "Too many requests.");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unhandled exception in Gateway pipeline.");
            if (context.Response.HasStarted)
                throw;

            await WriteAsync(context, StatusCodes.Status502BadGateway, "GW_UNHANDLED", "Gateway error.");
        }
    }

    private static async Task WriteAsync(HttpContext context, int status, string code, string message)
    {
        context.Response.Clear();
        context.Response.StatusCode = status;
        context.Response.ContentType = "application/json; charset=utf-8";

        var correlationId = context.Response.Headers[GatewayCorrelationIdMiddleware.HeaderName].ToString();
        var err = new GatewayError(code, message, correlationId);

        await context.Response.WriteAsJsonAsync(err);
    }
}
