using System;
using System.Threading.Tasks;
using Breizh360.Api.Metier.Contracts.Auth;
using Breizh360.Domaine.Auth.Users;

namespace Breizh360.Api.Services
{
    /// <summary>
    /// Simple token service used to issue access and refresh tokens.
    /// This implementation is deliberately minimal. A real implementation
    /// should issue properly signed JWTs and manage refresh tokens via
    /// secure storage. See the security recommendations in the project
    /// documentation for further guidance.
    /// </summary>
    public sealed class TokenService
    {
        /// <summary>
        /// Issues a new pair of tokens for the specified user. The tokens
        /// are random strings and should not be used in production.
        /// </summary>
        /// <param name="user">The authenticated user.</param>
        /// <returns>A response containing token type, access token, expiration and refresh token.</returns>
        public Task<AuthContractsTokenPairResponse> IssueAsync(User user)
        {
            if (user == null) throw new ArgumentNullException(nameof(user));

            // Generate pseudo-random tokens. In a real implementation these
            // values should be generated by a cryptographically secure JWT issuer.
            string accessToken = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
            string refreshToken = Convert.ToBase64String(Guid.NewGuid().ToByteArray());

            var response = new AuthContractsTokenPairResponse
            {
                AccessToken = accessToken,
                RefreshToken = refreshToken,
                ExpiresInSeconds = 3600
            };

            return Task.FromResult(response);
        }

        /// <summary>
        /// Issues a new access/refresh token pair based on a previous refresh token.
        /// A real implementation should validate the provided refresh token and
        /// rotate it appropriately. This stub simply ignores the input and
        /// returns new random tokens.
        /// </summary>
        /// <param name="refreshToken">The refresh token to rotate.</param>
        public Task<AuthContractsTokenPairResponse> RefreshAsync(string refreshToken)
        {
            // Rotate tokens by issuing brand new random values.
            string newAccessToken = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
            string newRefreshToken = Convert.ToBase64String(Guid.NewGuid().ToByteArray());

            var response = new AuthContractsTokenPairResponse
            {
                AccessToken = newAccessToken,
                RefreshToken = newRefreshToken,
                ExpiresInSeconds = 3600
            };

            return Task.FromResult(response);
        }
    }
}