using Breizh360.Gateway.Auth;
using Breizh360.Gateway.Common;
using Breizh360.Gateway.Errors;
using Breizh360.Gateway.Observability;
using Breizh360.Gateway.ReverseProxy;
using Microsoft.AspNetCore.HttpOverrides;

var builder = WebApplication.CreateBuilder(args);

// Logs (centralisé)
builder.AddGatewayLogging();

// Forwarded headers (IIS / reverse proxy). Safe defaults for intranet.
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    // NOTE: in intranet, you can lock down KnownNetworks/KnownProxies if needed.
});

// CORS / Rate limiting / YARP
builder.Services.AddGatewayCors(builder.Configuration, builder.Environment);
builder.Services.AddGatewayRateLimiting(builder.Configuration);
builder.Services.AddGatewayReverseProxy(builder.Configuration);

var app = builder.Build();

app.UseForwardedHeaders();

// Emit/propagate correlation id as early as possible
app.UseGatewayCorrelationId();

// Normalize errors generated by the Gateway itself
app.UseMiddleware<GatewayErrorMiddleware>();

app.UseHttpsRedirection();

app.UseCors(CommonCorsExtensions.PolicyName);

app.UseRateLimiter();

// Presence/format check only — API remains the source of authority for JWT validation.
app.UseMiddleware<GatewayJwtForwardingMiddleware>();

app.MapGet("/health", (HttpContext ctx) =>
{
    var correlationId = ctx.Response.Headers[GatewayCorrelationIdMiddleware.HeaderName].ToString();
    return Results.Ok(new { status = "ok", correlationId });
}).DisableRateLimiting();

// Apply rate limiting to proxy routes (global)
app.MapReverseProxy().RequireRateLimiting(CommonRateLimitingExtensions.PolicyName);

app.Run();
