// <auto-generated />
using System;
using Breizh360.Data;
using Breizh360.Domaine.Auth.Permissions;
using Breizh360.Domaine.Auth.RefreshTokens;
using Breizh360.Domaine.Auth.Roles;
using Breizh360.Domaine.Auth.Users;
using Breizh360.Domaine.Notifications.Entities;
using Breizh360.Domaine.Notifications.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Breizh360.Data.Migrations.Notifications;

[DbContext(typeof(Breizh360DbContext))]
[Migration("20260110110000_NotifInboxInitial")]
public partial class NotifInboxInitial
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity<Permission>(b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("Code").IsRequired().HasMaxLength(160);
            b.Property<DateTimeOffset>("CreatedAt");
            b.Property<DateTimeOffset?>("UpdatedAt");
            b.Property<bool>("IsDeleted").HasDefaultValue(false);
            b.Property<DateTimeOffset?>("DeletedAt");

            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("auth_permissions");
        });

        modelBuilder.Entity<Role>(b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("Name").IsRequired().HasMaxLength(120);
            b.Property<DateTimeOffset>("CreatedAt");
            b.Property<DateTimeOffset?>("UpdatedAt");
            b.Property<bool>("IsDeleted").HasDefaultValue(false);
            b.Property<DateTimeOffset?>("DeletedAt");

            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("auth_roles");
        });

        modelBuilder.Entity<User>(b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("Login").IsRequired().HasMaxLength(80);
            b.Property<string>("Email").IsRequired().HasMaxLength(320);
            b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512);

            b.Property<DateTimeOffset>("CreatedAt");
            b.Property<DateTimeOffset?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");

            b.Property<bool>("IsDeleted").HasDefaultValue(false);
            b.Property<DateTimeOffset?>("DeletedAt");
            b.Property<Guid?>("DeletedBy");

            b.HasKey("Id");
            b.HasIndex("Login").IsUnique();
            b.HasIndex("Email").IsUnique();
            b.ToTable("auth_users");
        });

        modelBuilder.Entity<UserRole>(b =>
        {
            b.Property<Guid>("UserId");
            b.Property<Guid>("RoleId");

            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.HasIndex("UserId");
            b.ToTable("auth_user_roles");
        });

        modelBuilder.Entity<RolePermission>(b =>
        {
            b.Property<Guid>("RoleId");
            b.Property<Guid>("PermissionId");

            b.HasKey("RoleId", "PermissionId");
            b.HasIndex("PermissionId");
            b.HasIndex("RoleId");
            b.ToTable("auth_role_permissions");
        });

        modelBuilder.Entity<RefreshToken>(b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("UserId");
            b.Property<string>("TokenHash").IsRequired().HasMaxLength(256);
            b.Property<string>("ReplacedByTokenHash").HasMaxLength(256);
            b.Property<DateTimeOffset>("ExpiresAt");
            b.Property<DateTimeOffset>("CreatedAt");
            b.Property<DateTimeOffset?>("RevokedAt");
            b.Property<string>("RevokedReason").HasMaxLength(200);
            b.Property<bool>("IsDeleted").HasDefaultValue(false);
            b.Property<DateTimeOffset?>("DeletedAt");

            b.HasKey("Id");
            b.HasIndex("TokenHash").IsUnique();
            b.HasIndex("UserId");
            b.ToTable("auth_refresh_tokens");
        });

        // Notifications (Inbox)
        var notificationIdConverter = new ValueConverter<NotificationId, Guid>(
            v => v.Value,
            v => NotificationId.From(v));

        var notificationTypeConverter = new ValueConverter<NotificationType, string>(
            v => v.Value,
            v => NotificationType.From(v));

        var idempotencyKeyConverter = new ValueConverter<IdempotencyKey?, string?>(
            v => v.HasValue ? v.Value.Value : null,
            v => string.IsNullOrWhiteSpace(v) ? null : IdempotencyKey.From(v));

        modelBuilder.Entity<Notification>(b =>
        {
            b.Property<NotificationId>("Id")
                .HasConversion(notificationIdConverter)
                .ValueGeneratedNever();

            b.Property<Guid>("UserId");

            b.Property<NotificationType>("Type")
                .IsRequired()
                .HasMaxLength(NotificationType.MaxLength)
                .HasConversion(notificationTypeConverter);

            b.Property<string>("Payload")
                .IsRequired()
                .HasMaxLength(Notification.PayloadMaxLength);

            b.Property<int>("Status");
            b.Property<bool>("IsRead").HasDefaultValue(false);

            b.Property<DateTimeOffset?>("ReadAtUtc");
            b.Property<DateTimeOffset>("CreatedAtUtc");
            b.Property<DateTimeOffset?>("UpdatedAtUtc");
            b.Property<DateTimeOffset?>("SentAtUtc");

            b.Property<int>("RetryCount").HasDefaultValue(0);
            b.Property<DateTimeOffset?>("NextAttemptAtUtc");
            b.Property<DateTimeOffset?>("ExpiresAtUtc");

            b.Property<IdempotencyKey?>("IdempotencyKey")
                .HasMaxLength(IdempotencyKey.MaxLength)
                .HasConversion(idempotencyKeyConverter);

            b.HasKey("Id");

            b.HasIndex("UserId", "CreatedAtUtc");
            b.HasIndex("UserId", "IsRead");
            b.HasIndex("Status", "NextAttemptAtUtc");
            b.HasIndex("UserId", "IdempotencyKey").IsUnique();

            b.ToTable("notif_inbox_notifications");
        });

        modelBuilder.Entity<UserRole>()
            .HasOne<User>()
            .WithMany()
            .HasForeignKey("UserId")
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserRole>()
            .HasOne<Role>()
            .WithMany()
            .HasForeignKey("RoleId")
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RolePermission>()
            .HasOne<Role>()
            .WithMany()
            .HasForeignKey("RoleId")
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RolePermission>()
            .HasOne<Permission>()
            .WithMany()
            .HasForeignKey("PermissionId")
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RefreshToken>()
            .HasOne<User>()
            .WithMany()
            .HasForeignKey("UserId")
            .OnDelete(DeleteBehavior.Cascade);
    }
}
